{
 "title": "Raspberry Pi K3S Nodes Overview",
 "description": "Dashboards for a K3S cluster where the Nodes consist of Raspberry Pi's (also does other kinds of nodes). Based on Dashboard 12869 (from matt7b7b).",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "HOST",
    "query": {
     "query": "label_values(kube_node_info, node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (node)(node_memory_MemTotal_bytes) - sum by (node)(node_memory_MemFree_bytes) - sum by (node)(node_memory_Buffers_bytes) - sum by (node)(node_memory_Cached_bytes))\r\n/ sum by (node)(node_memory_MemTotal_bytes) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 -(sum(rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) by(node)\r\n/ sum(rate(node_cpu_seconds_total[5m])) by(node) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "max(node_network_up) by (node)", "legendFormat": "{{kubernetes_node}}" }
   ]
  },
  {
   "title": "Node Temp",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(node_thermal_zone_temp) by (node)\r\n",
     "legendFormat": "{{kubernetes_node}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 -(sum(rate(node_cpu_seconds_total{mode=\"idle\"}[5m]))\r\n/ sum(rate(node_cpu_seconds_total[5m]))  * 100)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum (node_memory_MemTotal_bytes) - sum (node_memory_MemFree_bytes) - sum (node_memory_Buffers_bytes) - sum (node_memory_Cached_bytes))\r\n/ sum (node_memory_MemTotal_bytes) * 100"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{resource=\"memory\"}\r\n)"
    }
   ]
  },
  {
   "title": "Filesystem Available",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "\r\nsum(node_filesystem_free_bytes) by (node, device)\r\n",
     "legendFormat": "{{node}}({{device}})"
    }
   ]
  },
  {
   "title": "Total CPU Cores",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{resource=\"cpu\"}\r\n)"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_node_info) by (node, container_runtime_version, kernel_version, os_image, kubelet_version)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Request Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kubelet_http_requests_duration_seconds_sum[5m])) by (instance)",
     "legendFormat": "{{k3s_io_hostname}}"
    }
   ]
  },
  {
   "title": "Node Load 5",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_load5{node=~\"[[HOST]]\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Transmit Rate (In/Out)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{node=~\"[[HOST]]\"}[5m])) by (node)",
     "legendFormat": "{{node}} IN"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{node=~\"[[HOST]]\"}[5m])) by (node)",
     "legendFormat": "{{node}} OUT"
    }
   ]
  },
  {
   "title": "TCP Established Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{node=~\"[[HOST]]\"}",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}