---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: actions-runner-controller
  namespace: flux-system
spec:
  type: default
  url: https://actions-runner-controller.github.io/actions-runner-controller
  interval: 1h

