---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cameronrosier-cert
  namespace: default
spec:
  secretName: cameronrosier-tls
  issuerRef:
    name: letsencrypt-staging  # Start with staging, switch to letsencrypt-prod once working
    kind: ClusterIssuer
  dnsNames:
    - "cameronrosier.com"
