---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: home-pool
spec:
  blocks:
    - cidr: "192.168.2.50/28"
      # This gives you IPs from 192.168.2.48-192.168.2.63 (16 addresses)
      # Usable range: 192.168.2.49-192.168.2.62 (14 addresses)
