---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: loki-stack
      version: "2.10.x"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    # Loki configuration
    loki:
      enabled: true
      persistence:
        enabled: true
        size: 10Gi
        storageClassName: local-path
      config:
        auth_enabled: false
        chunk_store_config:
          max_look_back_period: 168h  # 7 days
        table_manager:
          retention_deletes_enabled: true
          retention_period: 168h  # 7 days
        limits_config:
          enforce_metric_name: false
          reject_old_samples: true
          reject_old_samples_max_age: 168h
          max_entries_limit_per_query: 5000
          max_query_series: 1000
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          memory: 512Mi
    
    # Promtail configuration
    promtail:
      enabled: true
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          memory: 128Mi
      config:
        clients:
          - url: http://{{ .Release.Name }}:3100/loki/api/v1/push
        snippets:
          pipelineStages:
            - cri: {}
            # Parse JSON logs if present
            - json:
                expressions:
                  level: level
                  msg: message
            - labels:
                level:
      tolerations:
        - effect: NoSchedule
          operator: Exists
    
    # Disable components we don't need
    grafana:
      enabled: false
    prometheus:
      enabled: false
    fluent-bit:
      enabled: false
    logstash:
      enabled: false
