---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: loki-stack
      version: "2.x"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    loki:
      enabled: true
      persistence:
        enabled: true
        storageClassName: longhorn
        size: 10Gi
      config:
        auth_enabled: false
        limits_config:
          retention_period: 168h
          max_query_series: 1000
        schema_config:
          configs:
            - from: "2024-01-01"
              store: tsdb
              object_store: filesystem
              schema: v13
              index:
                prefix: index_
                period: 24h
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          memory: 512Mi
    
    # Promtail already deployed separately
    promtail:
      enabled: false
    
    # Don't need Grafana (already have it)
    grafana:
      enabled: false
    
    # Don't need extra monitoring
    prometheus:
      enabled: false
    
    fluent-bit:
      enabled: false
    
    logstash:
      enabled: false
