---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: image-reflector-controller
  namespace: image-reflector-system
spec:
  interval: 1h
  chart:
    spec:
      chart: image-reflector-controller
      version: "0.32.x"
      sourceRef:
        kind: HelmRepository
        name: fluxcd-community
        namespace: flux-system
  install:
    crds: Create
    createNamespace: false
  upgrade:
    crds: CreateReplace
  values:
    resources:
      limits:
        memory: 256Mi
      requests:
        cpu: 10m
        memory: 64Mi
