---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: imagepolicies.image.toolkit.fluxcd.io
spec:
  group: image.toolkit.fluxcd.io
  names:
    kind: ImagePolicy
    listKind: ImagePolicyList
    plural: imagepolicies
    singular: imagepolicy
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        description: ImagePolicy is the Schema for the imagepolicies API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values.'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase.'
            type: string
          metadata:
            type: object
          spec:
            description: ImagePolicySpec defines the parameters for an image policy
            properties:
              filterTags:
                description: FilterTags enables filtering of tags based on a set of rules
                properties:
                  extract:
                    description: Extract allows a capture group to be extracted from the regex pattern, useful for things like v1.2.3 where only 1.2.3 is desired as the version. Named groups are not supported as the ordering is not guaranteed
                    type: string
                  pattern:
                    description: Pattern is a Regexp used to filter the tags in the repository
                    type: string
                type: object
              imageRepositoryRef:
                description: ImageRepositoryRef points at the object specifying the source of the image being scanned
                properties:
                  name:
                    type: string
                required:
                - name
                type: object
              policy:
                description: Policy gives the particulars of the policy to be followed in selecting the most recent image
                properties:
                  alphabetical:
                    description: Alphabetical set of rules to use for alphabetical ordering of the tags
                    properties:
                      order:
                        default: asc
                        description: Order specifies the sorting order of the tags. Given the letters of the numbers, ascending order would be `0-9A-Za-z` and descending order would be `z-aZ-A9-0`. Ordering is performed lexicographically using UTF-8 byte sequence
                        enum:
                        - asc
                        - desc
                        type: string
                    type: object
                  numerical:
                    description: Numerical set of rules to use for numerical ordering of the tags
                    properties:
                      order:
                        default: asc
                        description: Order specifies the sorting order of the tags. Lexicographically ascending order would be `0-9` and descending would be `9-0`
                        enum:
                        - asc
                        - desc
                        type: string
                    type: object
                  semver:
                    description: SemVer gives a semantic version range to check the tags against
                    properties:
                      range:
                        description: Range gives a semver range for the image tag; the highest version within the range that matches a tag in the repository will be used, which exact rules semver abides by rulesets and the way they compare versions is described at https://github.com/Masterminds/semver#checking-version-constraints
                        type: string
                    required:
                    - range
                    type: object
                type: object
            required:
            - imageRepositoryRef
            - policy
            type: object
          status:
            description: ImagePolicyStatus defines the observed state of ImagePolicy
            type: object
        required:
        - spec
        type: object
    subresources:
      status: {}
    additionalPrinterColumns:
    - jsonPath: .status.latestImage
      name: LatestImage
      type: string
