---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: imagerepositories.image.toolkit.fluxcd.io
spec:
  group: image.toolkit.fluxcd.io
  names:
    kind: ImageRepository
    listKind: ImageRepositoryList
    plural: imagerepositories
    singular: imagerepository
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        description: ImageRepository is the Schema for the imagerepositories API
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            description: ImageRepositorySpec defines the parameters for scanning an image repository
            properties:
              image:
                description: Image is the name of the image repository
                type: string
              interval:
                description: Interval is the length of time to wait between scans of the image repository
                pattern: ^([0-9]+(\.[0-9]+)?(ms|s|m|h))+$
                type: string
              secretRef:
                description: SecretRef can be given the name of a secret containing credentials to use for this ImageRepository. It should be in the same namespace as the ImageRepository
                properties:
                  name:
                    type: string
                required:
                - name
                type: object
            required:
            - image
            - interval
            type: object
          status:
            description: ImageRepositoryStatus defines the observed state of ImageRepository
            properties:
              canonicalImageName:
                description: CanonicalName is the name of the image repository with all the implied bits made explicit
                type: string
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      format: date-time
                      type: string
                    message:
                      maxLength: 32768
                      type: string
                    observedGeneration:
                      format: int64
                      type: integer
                    reason:
                      maxLength: 1024
                      minLength: 1
                      pattern: ^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$
                      type: string
                    status:
                      enum:
                      - "True"
                      - "False"
                      - Unknown
                      type: string
                    type:
                      maxLength: 316
                      pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Z0-9]|[a-z0-9])([-A-Z0-9_a-z0-9]*[A-Z0-9a-z0-9])?\.)+([A-Z]{2}|[0-9]{1,3})$|^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]$
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              lastScanTime:
                format: date-time
                type: string
              tags:
                description: Tags is the list of tags in the image repository
                items:
                  type: string
                type: array
            type: object
        type: object
    subresources:
      status: {}
    additionalPrinterColumns:
    - jsonPath: .spec.image
      name: Image
      type: string
    - jsonPath: .status.canonicalImageName
      name: CanonicalName
      type: string
    - jsonPath: .status.lastScanTime
      name: LastScanTime
      type: date
