---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: actions-runner-controller
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/home/infra/controllers/actions-runner-controller
  prune: true
  wait: true
  timeout: 5m  decryption:
    provider: sops
    secretRef:
      name: sops-age