---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: cert-manager-controller
    - name: actions-runner-controller
    - name: envoy-gateway
    - name: image-reflector-controller
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/home/apps
  prune: true
  wait: true
  timeout: 5m
  decryption:
    provider: sops
    secretRef:
      name: sops-age
